import type { BuildPhase, CoopProject } from '../types';
import type { Geometry } from './geometry';

/**
 * The 20 build phases. Content is largely static how-to guidance but a few
 * numbers (dimensions, box counts) are interpolated from the live design so the
 * printed instructions match the current plan. Time estimates assume the owner
 * plus one helper.
 */
export function computePhases(project: CoopProject, geo: Geometry): BuildPhase[] {
  const { coop, run, options } = project;
  const c = `${coop.widthFt}x${coop.depthFt} ft`;
  const r = `${run.widthFt}x${run.lengthFt} ft`;

  const phases: BuildPhase[] = [
    {
      id: 1,
      title: 'Site layout & leveling',
      summary: `Mark out the ${c} coop and ${r} run footprint and get the ground flat.`,
      tools: ['Tape measure', 'Mason line + stakes', 'Line level / 4 ft level', 'Shovel/rake'],
      materials: ['Batter boards / stakes', 'Marking paint', 'Gravel (optional under blocks)'],
      estimatedHours: 3,
      steps: [
        { text: `Stake the combined footprint (coop + attached run) and square it with the 3-4-5 method.` },
        { text: 'Rake high spots down and check level across the whole pad with a line level.' },
        { text: 'Where deck blocks land, dig a small flat pad and add a few inches of tamped gravel for drainage.' },
        { text: 'Confirm the run drains away from the coop, not toward it.' },
      ],
      commonMistakes: ['Skipping square — everything downstream fights you.', 'Building on a low spot that puddles.'],
      safetyNotes: ['Call 811 before digging even shallow block pads if utilities could be near.'],
    },
    {
      id: 2,
      title: 'Skids, deck blocks & foundation',
      summary: 'Set pressure-treated skids on deck blocks so the whole thing is level and movable — no post holes.',
      tools: ['4 ft level', 'Impact driver', 'Rubber mallet', 'Tape measure'],
      materials: ['4x4x12 PT skids', 'Deck blocks', 'Composite shims'],
      estimatedHours: 4,
      steps: [
        { text: 'Place deck blocks under each skid line (3 points per skid).' },
        { text: 'Lay the PT skids in the block saddles; shim until dead level in both directions.' },
        { text: 'Double-check diagonals are equal so the base is square.' },
      ],
      commonMistakes: ['Not leveling before framing — a racked floor telegraphs into every wall.'],
      safetyNotes: ['PT lumber: wear gloves, wash hands, do not breathe the sawdust.'],
    },
    {
      id: 3,
      title: 'Raised coop floor frame',
      summary: 'Build the joisted floor and sheath it with 3/4 in. plywood.',
      tools: ['Circular saw', 'Impact driver', 'Speed square', 'Chalk line', 'Caulk gun'],
      materials: ['2x8 joists', '2x8 rim boards', 'Joist hangers', '3/4" plywood', 'Subfloor adhesive', '3" screws'],
      estimatedHours: 5,
      steps: [
        { text: `Build the ${coop.widthFt} ft rim box, then hang the joists @ ${coop.joistSpacingIn}" OC.` },
        { text: 'Glue and screw the 3/4" plywood subfloor; stagger the seams over joists.' },
        { text: 'Seal the plywood edges — this floor lives outdoors until walls go up.' },
      ],
      commonMistakes: ['Forgetting adhesive (squeaky floor).', 'Sheathing seams not landing on a joist.'],
      safetyNotes: ['Support long plywood cuts so they do not bind the saw.'],
    },
    {
      id: 4,
      title: 'Vinyl plank flooring (owner-supplied)',
      summary: 'Install your waterproof vinyl plank over the subfloor before walls trap you out.',
      tools: ['Utility knife', 'Tapping block', 'Straightedge', 'Speed square'],
      materials: ['Owner-supplied waterproof vinyl plank', 'Transition/edge trim'],
      estimatedHours: 3,
      steps: [
        { text: 'Sweep the subfloor perfectly clean; a grain of grit shows through vinyl.' },
        { text: 'Run planks the long direction; leave a small expansion gap at the walls (walls + trim hide it).' },
        { text: 'Run the plank slightly up under where the base plates land, or trim tight so bedding cannot wick underneath.' },
      ],
      commonMistakes: ['Installing flooring after the walls (much harder to fit).', 'No expansion gap.'],
      safetyNotes: ['Fresh blades only — dull knives slip.'],
    },
    {
      id: 5,
      title: 'Coop wall framing',
      summary: `Frame four walls: tall front (${coop.frontWallHeightFt} ft) to short back (${coop.backWallHeightFt} ft) for the shed slope.`,
      tools: ['Circular saw', 'Impact driver', 'Speed square', 'Level'],
      materials: ['2x4 studs', '2x4 plates', '3" screws'],
      estimatedHours: 6,
      steps: [
        { text: `Frame each wall flat on the deck @ ${coop.studSpacingIn}" OC; frame the human door and window/vent rough openings now.` },
        { text: 'Stand, brace, plumb, and screw the walls together at the corners.' },
        { text: 'Add the sloped side-wall top plates so the rafters have a continuous bearing.' },
      ],
      commonMistakes: ['Rough openings too tight for the door/auto-door.', 'Walls not plumb before siding.'],
      safetyNotes: ['Have your helper steady walls while standing them — they catch wind.'],
    },
    {
      id: 6,
      title: 'Coop siding',
      summary: 'Hang the exterior siding and seal every edge.',
      tools: ['Circular saw', 'Impact driver', 'Caulk gun', 'Paint roller'],
      materials: ['Siding sheets', '1x4 trim', '2-1/2" screws', 'Paint or house wrap', 'Caulk'],
      estimatedHours: 6,
      steps: [
        { text: 'Hang full sheets first; cut around openings.' },
        { text: 'Trim the corners and openings with 1x4; caulk all seams.' },
        { text: 'Prime + paint (or wrap/batten if OSB) — no bare edges left exposed.' },
      ],
      commonMistakes: ['Leaving siding edges unsealed (delamination).', 'Gaps at trim a mouse can use.'],
      safetyNotes: ['Paint with ventilation; follow the can\'s cure times.'],
    },
    {
      id: 7,
      title: 'Coop roof framing',
      summary: 'Set the shed rafters and purlins.',
      tools: ['Circular saw', 'Impact driver', 'Speed square', 'Ladder'],
      materials: ['2x6 rafters', '2x4 purlins', '3" screws'],
      estimatedHours: 5,
      steps: [
        { text: `Cut the bird\'s-mouths to the ${geo.coopRoofPitchPer12.toFixed(1)}:12 pitch and set rafters @ ${coop.rafterSpacingIn}" OC.` },
        { text: `Add the ${coop.roofOverhangFt} ft overhang; screw on the horizontal purlins for the panels.` },
        { text: 'Brace the roof plane square before panels.' },
      ],
      commonMistakes: ['Inconsistent bird\'s-mouths → wavy roof.', 'Forgetting overhang (rain runs down the siding).'],
      safetyNotes: ['Work off a stable ladder or scaffold; never the top rung.'],
    },
    {
      id: 8,
      title: 'Corrugated roof installation (coop)',
      summary: 'Screw down the corrugated panels with gasketed screws and foam closures.',
      tools: ['Impact driver', 'Fine-tooth blade / snips', 'Ladder', 'Chalk line'],
      materials: ['Corrugated panels', 'Foam closure strips', 'Gasketed panel screws'],
      estimatedHours: 4,
      steps: [
        { text: 'Lay foam closures on the top plate/purlins; overlap panels one corrugation with the prevailing wind.' },
        { text: 'Screw at the top of the corrugation, into purlins, with the neoprene washer just snug (not crushed).' },
        { text: 'Close both eaves with foam strips so nothing crawls under the panels.' },
      ],
      commonMistakes: ['Screwing the valley (leaks).', 'Overtightening (cracks PVC).'],
      safetyNotes: ['Panels are slippery and have sharp edges — gloves + a helper on the ground.'],
    },
    {
      id: 9,
      title: 'Coop doors, window & vent flap',
      summary: 'Hang the human door and build the window/vent with a closable winter flap.',
      tools: ['Impact driver', 'Chisel', 'Snips', 'Drill'],
      materials: ['Hinges', 'Predator latch', 'Barrel bolt', 'Hardware cloth', 'Vent-flap hinge/hasp'],
      estimatedHours: 5,
      steps: [
        { text: 'Build/hang the human door; add the lockable latch + barrel bolt.' },
        { text: 'Cover the window/vent opening with 1/2" hardware cloth, screwed with fender washers.' },
        { text: 'Add the hinged flap/shutter over the vent for winter wind and driving storms.' },
      ],
      commonMistakes: ['Stapling wire only (predators pull staples).', 'Vent with no way to close it in a blizzard.'],
      safetyNotes: ['Hardware cloth cuts — file the edges or fold them under trim.'],
    },
    {
      id: 10,
      title: 'Outside-access nesting boxes',
      summary: `Build/mount ${options.nestingBoxCount} ${options.nestingBoxType.replace('-', ' ')} boxes with an exterior lid.`,
      tools: ['Circular saw', 'Impact driver', 'Level'],
      materials: ['1/2" plywood (or premade units)', 'Hinges', 'Latch', options.nestingBoxType === 'diy-rollaway' ? 'Nest pad liner' : 'Bedding'],
      estimatedHours: options.nestingBoxType === 'premade-rollaway' ? 2 : 5,
      steps: [
        { text: 'Frame the exterior opening below the roosts so hens do not roost/poop in the boxes.' },
        { text: 'Mount the boxes with a rain-shedding, latched exterior lid for egg collection.' },
        options.nestingBoxType === 'diy-rollaway'
          ? { text: 'Set a gentle back-slope with a liner so eggs roll to a padded collection tray.' }
          : { text: 'Add a lip and bedding; keep boxes dark and private.' },
      ],
      commonMistakes: ['Boxes higher than the roosts (birds sleep in them).', 'Lid that leaks onto the eggs.'],
      safetyNotes: ['Latch the exterior lid — it is another door a raccoon will test.'],
    },
    {
      id: 11,
      title: 'Roosts',
      summary: 'Install 2x4 roosts flat-side up so big birds cover their toes in winter.',
      tools: ['Circular saw', 'Impact driver', 'Level'],
      materials: ['2x4 roost bars', 'Removable brackets'],
      estimatedHours: 2,
      steps: [
        { text: 'Mount roosts higher than the nesting boxes, all at one level.' },
        { text: 'Round the top edges; set on removable brackets for easy cleaning.' },
        { text: 'Allow ~10 in. of roost per bird.' },
      ],
      commonMistakes: ['Skinny round roosts (frostbite on large breeds).', 'Roosts over the waterer/feeder.'],
      safetyNotes: [],
    },
    {
      id: 12,
      title: 'Automatic chicken door',
      summary: 'Install and program the auto door — treat it as security-critical.',
      tools: ['Drill', 'Level', 'Screwdriver'],
      materials: ['Auto door kit', 'Screws', 'Caulk'],
      estimatedHours: 2,
      steps: [
        { text: 'Mount the track plumb so the door seals with no side gaps.' },
        { text: 'Program the timer/light sensor; verify a full close after dark.' },
        { text: 'Keep the coop itself predator-tight as a backup and add a manual slide.' },
      ],
      commonMistakes: ['Track not plumb (door jams open).', 'Relying on the auto door as the only barrier.'],
      safetyNotes: ['Do a weekly close test — a stuck-open door at dusk is a buffet.'],
    },
    {
      id: 13,
      title: 'Run modular wall panels',
      summary: `Build ${Math.max(1, Math.ceil((geo.runWallPerimeterFt - geo.runSharedWallFt) / run.panelWidthFt))} bolt-together ${run.panelWidthFt} ft wall panels + the run door.`,
      tools: ['Circular saw', 'Impact driver', 'Wrench', 'Level'],
      materials: ['2x4 framing', '4x4 PT posts', 'Carriage bolts', 'Door hinges/latch'],
      estimatedHours: 8,
      steps: [
        { text: 'Build identical 2x4 panel frames on a flat surface (batch-cut for speed).' },
        { text: 'Set PT corner posts/sill on deck blocks; bolt panels together so they can unscrew to move.' },
        { text: 'Hang the walk-in run door with a self-closing lockable latch.' },
      ],
      commonMistakes: ['Panels not identical (nothing lines up).', 'Screwing instead of bolting the joints you want to move later.'],
      safetyNotes: ['Brace tall panels immediately — they are sails in wind.'],
    },
    {
      id: 14,
      title: 'Run roof panels',
      summary: 'Set the center beam, rafters, purlins, and corrugated run roof.',
      tools: ['Circular saw', 'Impact driver', 'Ladder', 'Chalk line'],
      materials: ['Doubled 2x8 beam', '2x6 rafters', '2x4 purlins', 'Corrugated panels', 'Panel screws'],
      estimatedHours: 8,
      steps: [
        { text: 'Set the doubled 2x8 center beam on its posts; crown up.' },
        { text: `Run 2x6 rafters @ ${run.rafterSpacingIn}" OC over the beam; add purlins.` },
        { text: 'Screw down the corrugated panels with gasketed screws; close the eaves.' },
      ],
      commonMistakes: ['Under-supporting the 12 ft span (snow sag).', 'Panels with no eave closures.'],
      safetyNotes: ['This is the heaviest overhead work — two people, good ladders.'],
    },
    {
      id: 15,
      title: 'Hardware cloth installation',
      summary: 'Wrap every run wall (and coop vents) in 1/2 in. hardware cloth.',
      tools: ['Aviation snips', 'Staple gun', 'Impact driver', 'Gloves'],
      materials: ['1/2" hardware cloth', 'Poultry staples', 'Screws + fender washers'],
      estimatedHours: 8,
      steps: [
        { text: 'Cover every opening with 1/2" hardware cloth, wire on the INSIDE of the framing.' },
        { text: 'Fasten every ~2 in. with staples PLUS screws-and-washers at all seams and edges.' },
        { text: 'Overlap panels 2 in. and wire the seams shut — no gaps over 1/2 in. anywhere.' },
      ],
      commonMistakes: ['Chicken wire "to save money".', 'Staples only (predators peel it back).', 'Gaps at the roofline.'],
      safetyNotes: ['Sharp wire — gloves + eye protection; fold or trim every cut edge.'],
    },
    {
      id: 16,
      title: 'Anti-dig apron',
      summary: 'Stop diggers with an outward ground apron (or buried skirt).',
      tools: ['Snips', 'Staple gun', 'Mallet', 'Gloves'],
      materials: ['1/2" hardware cloth', 'Landscape staples'],
      estimatedHours: 4,
      steps: [
        { text: `Run a ${options.antiDigApronFt} ft skirt of hardware cloth flat on the ground, outward from the base.` },
        { text: 'Pin it down with landscape staples; grass grows through and hides it.' },
        { text: 'Overlap and wire the apron to the wall wire so there is no seam to exploit.' },
      ],
      commonMistakes: ['Apron too narrow (predators start digging further out).', 'Apron not tied to the wall wire.'],
      safetyNotes: ['Staple flush so nobody trips or catches a mower.'],
    },
    {
      id: 17,
      title: 'Latches & predator-proofing inspection',
      summary: 'Walk the whole build like a raccoon and a fox would.',
      tools: ['Flashlight', 'Your hands'],
      materials: ['Extra latches/hasps as needed'],
      estimatedHours: 2,
      steps: [
        { text: 'Shake every door and panel; anything that rattles or has play gets reinforced.' },
        { text: 'Check every seam and corner for gaps > 1/2 in.; look especially at the roofline and door edges.' },
        { text: 'Confirm both doors have lockable latches and the auto door seals.' },
      ],
      commonMistakes: ['Trusting one latch.', 'Missing the small gap under a door or at a corner.'],
      safetyNotes: [],
    },
    {
      id: 18,
      title: 'Hanging feeder rail / chains',
      summary: 'Suspend feeders so rats and rain cannot get an easy meal.',
      tools: ['Drill', 'Level'],
      materials: ['Screw eyes + chain (or feeder rail)', 'Feeders'],
      estimatedHours: 2,
      steps: [
        { text: 'Hang feeders at the birds\' back height on adjustable chains or a rail.' },
        { text: 'Keep feed in metal, rodent-proof containers off the ground inside the run.' },
        { text: 'Sweep spilled feed — spillage is what actually draws rats.' },
      ],
      commonMistakes: ['Feeder on the ground (rat magnet).', 'Storing feed in chewable bins.'],
      safetyNotes: [],
    },
    {
      id: 19,
      title: 'Heated water & extension-cord setup',
      summary: 'Power the heated waterer safely with an outdoor cord + GFCI.',
      tools: ['None (no hardwiring)'],
      materials: ['Outdoor 12-ga cord', 'GFCI adapter', 'Weatherproof cover', 'Heated waterer base', 'Cord protector'],
      estimatedHours: 2,
      steps: [
        { text: 'Run ONE continuous outdoor-rated cord from a GFCI outlet; no daisy-chains.' },
        { text: 'Keep the plugged connection dry and off the ground in a weatherproof in-use cover.' },
        { text: 'Route the cord in a protector where birds and mowers cannot reach it. Leave a service loop for future lighting.' },
      ],
      commonMistakes: ['Indoor cords outdoors.', 'No GFCI.', 'Connection sitting in a puddle.'],
      safetyNotes: ['Water + electricity: GFCI is non-negotiable. Inspect the cord each season.'],
    },
    {
      id: 20,
      title: 'Final checklist & move-in',
      summary: 'Bedding down, birds in, and a first-week watch.',
      tools: ['Broom'],
      materials: ['Pine shavings', 'Feeders/waterers', 'Grit/oyster shell'],
      estimatedHours: 2,
      steps: [
        { text: 'Bed the coop over the vinyl floor; fill nesting boxes.' },
        { text: 'Do a final predator walk-around at dusk (that is when they come).' },
        { text: 'Introduce the flock; watch the auto door close for the first several nights.' },
      ],
      commonMistakes: ['Moving birds in before the last gap is closed.'],
      safetyNotes: [],
    },
  ];

  return phases;
}
